### ISSUE TITLE
Error occurred when i want to see the tensorboard

### ISSUE THREAD

**Issue by zhouweii234** [z-x-yang/CFBI#44]
I want to see the tensorboard when finetune CFBI on DAVIS 2017，so I change the `self.TRAIN_TBLOG`  in the file resnet101_cfbi_davis_finetune.py to be True. But after the change ,an error Error occurred:

> Traceback (most recent call last):
  File "tools/train_net.py", line 73, in <module>
    main()
  File "tools/train_net.py", line 70, in main
    mp.spawn(main_worker, nprocs=cfg.TRAIN_GPUS, args=(cfg,))
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 
> 
> -- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/root/projects/code/full_CFBI/full_CFBI/tools/train_net.py", line 13, in main_worker
    trainer.sequential_training()
  File "./networks/engine/train_manager.py", line 275, in sequential_training
    self.process_log(
  File "./networks/engine/train_manager.py", line 343, in process_log
    for seq_step, running_loss, running_iou in zip(range(running_losses), running_losses, running_ious):
TypeError: 'list' object cannot be interpreted as an integer

Do you know how I can solve this error?

**Comment by z-x-yang** [comment]
range(running_losses) -> range(len(running_losses))

**Comment by zhouweii234** [comment]
It works, thank you very much for your reply!
